import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import { TooltipProvider } from "@/components/ui/tooltip";
import { AuthSessionProvider } from "@/core/auth";

import "./globals.css";

const outfit = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${outfit.variable} h-full font-sans antialiased`}
      suppressHydrationWarning
    >
      <body className='flex min-h-full flex-col' suppressHydrationWarning>
        <AuthSessionProvider>
          <TooltipProvider>{children}</TooltipProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
